import { useState } from 'react'
import { ArrowLeft, Check, ChevronRight, Clock3, Flame, Heart, Plus } from 'lucide-react'
import { text, translations } from '../data/translations'
import { scaleIngredientAmount } from '../utils/portion'

const accents = { sunset: 'from-[#ff9f68] to-[#e85d3f]', lime: 'from-[#b5cc67] to-[#49734b]', coral: 'from-[#ee8069] to-[#a83242]', chilli: 'from-[#f27657] to-[#b92931]', gold: 'from-[#f2c15f] to-[#d77736]', yellow: 'from-[#f3d067] to-[#d89231]', orange: 'from-[#e8a45d] to-[#c65e33]', brown: 'from-[#b88865] to-[#754538]', honey: 'from-[#e8b55a] to-[#bd682f]', pepper: 'from-[#879d91] to-[#364f48]' }

export function MissingIngredients({ ingredients, onAddMissing, servingCount, lang }) {
  if (!ingredients.length) return null
  return <button className="grocery-add-button detail-grocery-add" onClick={() => onAddMissing(ingredients, servingCount)}><Plus size={14} /> {translations[lang].ui.addToGrocery}</button>
}

export function PairingSection({ pairings, onOpenRecipe, lang }) {
  const t = translations[lang]; if (!pairings.length) return null
  return <section className="pairings-section"><div className="section-heading"><div><span className="section-kicker">{t.ui.pairings}</span><h2>{t.ui.completeMeal}</h2></div><span className="sort-label">{pairings.length} {t.ui.pairingsCount}</span></div><p className="pairings-copy">{t.ui.pairingHint}</p><div className="pairings-row">{pairings.map(pairing => <button className="pairing-card" key={pairing.id} onClick={() => onOpenRecipe(pairing)}><div className={`pairing-art bg-gradient-to-br ${accents[pairing.accent] || accents.sunset}`}><span>{text(pairing.name, lang).split(' ').slice(0, 2).map(word => word[0]).join('')}</span></div><div><strong>{text(pairing.name, lang)}</strong><small><Clock3 size={12} /> {pairing.time} min</small></div><ChevronRight size={16} /></button>)}</div></section>
}

export default function RecipeDetail({ recipe, recipes, onBack, isFavorite, onToggleFavorite, onOpenRecipe, onAddMissing, lang = 'ms', onToggleLanguage }) {
  const t = translations[lang]; const [checked, setChecked] = useState([]); const [selectedServings, setSelectedServings] = useState(recipe.defaultServings); const name = text(recipe.name, lang); const toggle = id => setChecked(items => items.includes(id) ? items.filter(item => item !== id) : [...items, id]); const pairings = (recipe.pairings || []).map(id => recipes.find(item => item.id === id)).filter(Boolean); const missingCore = recipe.missingCore ?? recipe.ingredients.filter(item => !item.staple && !item.optional)
  return <div className="screen detail-screen"><div className={`detail-hero hero-${recipe.accent}`}><button className="detail-back" onClick={onBack} aria-label={lang === 'ms' ? 'Kembali' : 'Back'}><ArrowLeft size={20} /></button>{onToggleLanguage && <button className="language-toggle detail-language-toggle" onClick={onToggleLanguage}><b className={lang === 'ms' ? 'active' : ''}>BM</b><span>|</span><b className={lang === 'en' ? 'active' : ''}>EN</b></button>}<button className="like-button" onClick={() => onToggleFavorite(recipe.id)} aria-label={isFavorite ? t.ui.removeFavorite : t.ui.saveRecipe}><Heart size={20} fill={isFavorite ? 'currentColor' : 'none'} /></button><div className="hero-initials">{name.split(' ').slice(0, 2).map(word => word[0]).join('')}</div><div className="hero-caption"><span>{text(recipe.style, lang)}</span><h1>{name}</h1></div></div><main className="content detail-content"><div className="detail-meta"><span><Clock3 size={16} /> {recipe.time} min</span><span><Flame size={16} /> {text(recipe.difficulty, lang)}</span><span>{selectedServings} {t.ui.servings}</span></div><section className="detail-section"><div className="section-heading"><div><span className="section-kicker">{t.ui.needed}</span><h2>{t.ui.ingredients}</h2></div><span className="progress">{checked.length}/{recipe.ingredients.length}</span></div><div className="portion-bar"><span>{t.ui.portion}</span><div>{t.ui.pax.map((label, index) => { const count = [1, 2, 4][index]; return <button key={count} onClick={() => setSelectedServings(count)} className={selectedServings === count ? 'portion-button active' : 'portion-button'}>{label}</button> })}</div></div><div className="checklist">{recipe.ingredients.map((item, index) => <button key={`${item.id}-${index}`} onClick={() => toggle(index)} className={checked.includes(index) ? 'check-row checked' : 'check-row'}><span className="check-box">{checked.includes(index) && <Check size={14} />}</span><span>{text(item.name, lang)}</span><small>{scaleIngredientAmount(item.amount, recipe.defaultServings, selectedServings)}</small></button>)}</div><MissingIngredients ingredients={missingCore} servingCount={selectedServings} onAddMissing={(ingredients, servings) => onAddMissing(recipe, ingredients, servings)} lang={lang} /></section><section className="detail-section"><h2>{lang === 'ms' ? 'Cara memasak' : 'Instructions'}</h2><ol className="steps-list">{recipe.steps.map((step, index) => <li key={index}>{text(step, lang)}</li>)}</ol><p className="recipe-tip">{text(recipe.tip, lang)}</p></section><PairingSection pairings={pairings} onOpenRecipe={onOpenRecipe} lang={lang} /></main></div>
}
