import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, ChevronRight, Heart, Leaf, Search, Sparkles, ToggleLeft, ToggleRight } from 'lucide-react'
import { registerSW } from 'virtual:pwa-register'
import BottomNav from './components/BottomNav'
import RecipeCard from './components/RecipeCard'
import RecipeDetail from './components/RecipeDetail'
import { scaleIngredientAmount } from './utils/portion'
import { groups, ingredientOptions, recipes, stapleIngredients } from './data/recipes'
import { text, translations } from './data/translations'

const allStapleIds = stapleIngredients.map(item => item.id)
const readStorage = (key, fallback) => { try { const value = window.localStorage.getItem(key); return value === null ? fallback : JSON.parse(value) } catch { return fallback } }
const writeStorage = (key, value) => { try { window.localStorage.setItem(key, JSON.stringify(value)) } catch { /* Storage may be unavailable. */ } }
function matchesFilter(recipe, query, filter, favorites, lang) { const name = text(recipe.name, lang); const style = text(recipe.style, lang); const rawStyle = text(recipe.style, 'ms'); const searchable = `${name} ${style}`.toLowerCase(); const category = filter === 'Semua' || filter === 'All' ? true : filter === 'Favorite' || filter === 'Kegemaran' || filter === 'Favorites' ? favorites.includes(recipe.id) : filter === 'Bujang Express' || filter === 'Express' ? rawStyle === 'Bujang/Express' : filter === 'Masakan Kampung' || filter === 'Traditional' ? rawStyle === 'Masakan Kampung' : filter === 'Air Fryer Only' || filter === 'Air Fryer' ? recipe.airFryer : rawStyle === filter; return searchable.includes(query.toLowerCase()) && category }
function Filters({ query, setQuery, filter, setFilter, lang }) { const t = translations[lang]; const options = [[t.categories.all, 'Semua'], [t.categories.express, 'Bujang Express'], [t.categories.traditional, 'Masakan Kampung'], [t.categories.airFryer, 'Air Fryer Only']]; return <><div className="search-box"><Search size={19} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t.ui.searchPlaceholder} /><kbd>/</kbd></div><div className="filter-row flex overflow-x-auto flex-nowrap scrollbar-none px-4 pr-8 py-2 space-x-2 w-full items-center">{options.map(([label, value]) => <button key={value} onClick={() => setFilter(value)} className={filter === value ? 'filter-chip active' : 'filter-chip'}>{label}</button>)}</div></> }
function Header({ title, subtitle, lang, onToggleLanguage }) { return <div className="shrink-0"><header className="page-header"><div className="header-mark"><Leaf size={15} fill="currentColor" /><span>{translations[lang].ui.pantryMark}</span><button className="language-toggle" onClick={onToggleLanguage} aria-label={lang === 'ms' ? 'Tukar ke English' : 'Switch to Bahasa Melayu'}><b className={lang === 'ms' ? 'active' : ''}>BM</b><span>|</span><b className={lang === 'en' ? 'active' : ''}>EN</b></button></div><h1>{title}</h1><p>{subtitle}</p></header></div> }
function GroceryList({ groceryList, onToggleItem, onClearChecked, onClearAll, lang, onToggleLanguage }) { const t = translations[lang]; return <div className="screen"><Header title={t.headers.grocery[0]} subtitle={t.headers.grocery[1]} lang={lang} onToggleLanguage={onToggleLanguage} /><main className="content grocery-content"><div className="grocery-toolbar"><span>{groceryList.filter(item => !item.checked).length} {t.ui.groceryCount}</span>{groceryList.some(item => item.checked) && <button onClick={onClearChecked}>{t.ui.clearChecked}</button>}</div>{groceryList.length ? <><div className="grocery-items">{groceryList.map(item => <button key={item.id} className={item.checked ? 'grocery-item checked' : 'grocery-item'} onClick={() => onToggleItem(item.id)}><span className="check-box">{item.checked && <Check size={14} />}</span><span><strong>{text(item.name, lang)}</strong><small>{item.amount} | {text(item.recipeTitle, lang)}</small></span></button>)}</div><button className="clear-all-button" onClick={onClearAll}>{t.ui.clearAll}</button></> : <div className="empty-state"><span className="empty-list-icon"><Check size={22} /></span><p>{t.ui.emptyGrocery}</p><span>{t.ui.emptyGroceryHint}</span></div>}</main></div> }

function Matcher({ openRecipe, query, setQuery, filter, setFilter, favorites, toggleFavorite, lang, onToggleLanguage }) {
  const t = translations[lang]; const [staplesOn, setStaplesOn] = useState(() => readStorage('masakapa-staples-on', true)); const [selected, setSelected] = useState(() => readStorage('masakapa-selected-ingredients', ['chicken', 'potato', 'turmeric']))
  useEffect(() => writeStorage('masakapa-staples-on', staplesOn), [staplesOn]); useEffect(() => writeStorage('masakapa-selected-ingredients', selected), [selected])
  const matches = useMemo(() => recipes.map(recipe => { const core = recipe.ingredients.filter(item => !item.staple && !item.optional); const available = new Set(staplesOn ? [...selected, ...allStapleIds] : selected); const missingCore = core.filter(item => !available.has(item.id)); const matchedCoreCount = core.length - missingCore.length; const matchPercentage = core.length ? Math.round(matchedCoreCount / core.length * 100) : 100; return { recipe, missingCore, missingOptional: recipe.ingredients.filter(item => item.optional && !available.has(item.id)), matchPercentage } }).filter(match => match.missingCore.length <= 2 && match.matchPercentage >= 40).sort((a, b) => (b.matchPercentage - a.matchPercentage) || ((a.recipe.cookTimeMins ?? a.recipe.time) - (b.recipe.cookTimeMins ?? b.recipe.time))), [selected, staplesOn])
  const visible = matches.filter(match => matchesFilter(match.recipe, query, filter, favorites, lang)); return <div className="screen"><Header title={t.headers.matcher[0]} subtitle={t.headers.matcher[1]} lang={lang} onToggleLanguage={onToggleLanguage} /><main className="content pb-24"><section className="staples-panel"><div><span className="section-kicker">{t.ui.pantryMark}</span><h2>{t.ui.pantry}</h2><p>{t.ui.pantryHint}</p></div><button aria-label={t.ui.pantry} onClick={() => setStaplesOn(on => !on)} className="toggle">{staplesOn ? <ToggleRight size={40} /> : <ToggleLeft size={40} />}<b>{staplesOn ? t.ui.on : t.ui.off}</b></button><div className="staple-list">{stapleIngredients.map(item => <span key={item.id} className={staplesOn ? 'mini-pill on' : 'mini-pill'}>{text(item.name, lang)}</span>)}</div></section><section className="ingredient-section"><div className="section-heading"><div><span className="section-kicker">{t.ui.fridge}</span><h2>{t.ui.chooseIngredients}</h2></div><span className="selected-count">{selected.length} {t.ui.selected}</span></div>{groups.map(group => <div className="ingredient-group" key={group}><h3>{t.groups[group]}</h3><div className="chip-grid">{ingredientOptions.filter(item => item.group === group).map(item => <button key={item.id} onClick={() => setSelected(items => items.includes(item.id) ? items.filter(value => value !== item.id) : [...items, item.id])} className={selected.includes(item.id) ? 'ingredient-chip selected' : 'ingredient-chip'}>{selected.includes(item.id) && <Check size={14} />}{text(item.name, lang)}</button>)}</div></div>)}</section><section className="results-section"><Filters query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} lang={lang} /><div className="section-heading results-heading"><div><span className="section-kicker">{t.ui.recommendations}</span><h2>{visible.length} {t.ui.matches}</h2></div><Sparkles size={21} className="sparkle" /></div><div className="recipe-list flex flex-col space-y-2 px-4 pb-24">{visible.map(match => <RecipeCard key={match.recipe.id} recipe={match.recipe} match={match} isFavorite={favorites.includes(match.recipe.id)} onToggleFavorite={toggleFavorite} onClick={openRecipe} lang={lang} />)}</div></section></main></div>
}

function Discover({ openRecipe, query, setQuery, filter, setFilter, favorites, toggleFavorite, lang, onToggleLanguage }) { const t = translations[lang]; const visible = recipes.filter(recipe => matchesFilter(recipe, query, filter, favorites, lang)); const favoriteFilter = filter === 'Favorite' || filter === 'Kegemaran' || filter === 'Favorites'; return <div className="screen"><Header title={t.headers.discover[0]} subtitle={t.headers.discover[1]} lang={lang} onToggleLanguage={onToggleLanguage} /><main className="content pb-24"><Filters query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} lang={lang} /><div className="discover-intro"><div><span className="section-kicker">{t.ui.today}</span><h2>{visible.length} {t.ui.choices}</h2></div><span className="sort-label">{t.ui.easiest} <ChevronRight size={16} /></span></div>{favoriteFilter && visible.length === 0 ? <div className="empty-state"><p>{lang === 'ms' ? 'Tiada resipi kegemaran lagi.' : 'No favorited recipes yet.'}</p></div> : <div className="recipe-list flex flex-col space-y-2 px-4 pb-24">{visible.map(recipe => <RecipeCard key={recipe.id} recipe={recipe} isFavorite={favorites.includes(recipe.id)} onToggleFavorite={toggleFavorite} onClick={openRecipe} lang={lang} />)}</div>}</main></div> }
function Favorites({ openRecipe, favorites, toggleFavorite, lang, onToggleLanguage, onExplore }) { const isMalay = lang === 'ms'; const savedRecipes = recipes.filter(recipe => favorites.includes(recipe.id)); return <div className="screen"><Header title={isMalay ? 'Resipi Kegemaran' : 'Saved Recipes'} subtitle={isMalay ? 'Koleksi resipi tersimpan anda' : 'Your personal recipe collection'} lang={lang} onToggleLanguage={onToggleLanguage} /><main className="content pb-24">{savedRecipes.length ? <div className="recipe-list flex flex-col space-y-2 px-4 pb-24">{savedRecipes.map(recipe => <RecipeCard key={recipe.id} recipe={recipe} isFavorite={true} onToggleFavorite={toggleFavorite} onClick={openRecipe} lang={lang} />)}</div> : <div className="mx-4 mt-8 rounded-2xl border border-stone-100 bg-white p-6 text-center shadow-sm"><span className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-rose-50 text-rose-500"><Heart size={24} fill="currentColor" /></span><p className="text-sm leading-6 text-stone-600">{isMalay ? 'Belum ada resipi kegemaran. Tekan ikon hati pada mana-mana resipi untuk simpan di sini.' : 'No saved recipes yet. Tap the heart icon on any recipe to bookmark it here.'}</p><button className="mt-5 rounded-lg bg-[#d6573a] px-4 py-2 text-xs font-bold text-white" onClick={onExplore}>{isMalay ? 'Cari Resipi' : 'Explore Recipes'}</button></div>}</main></div> }

export default function App() {
  const mainRef = useRef(null); const [lang, setLang] = useState(() => readStorage('masakapa-language', 'ms') === 'en' ? 'en' : 'ms'); const [screen, setScreen] = useState('matcher'); const [activeRecipe, setActiveRecipe] = useState(null); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Semua'); const [favorites, setFavorites] = useState(() => readStorage('masakapa-favorites', [])); const [groceryList, setGroceryList] = useState(() => readStorage('masakapa-grocery-list', [])); const [updateAvailable, setUpdateAvailable] = useState(false); const [updateSW] = useState(() => registerSW({ immediate: true, onNeedRefresh: () => setUpdateAvailable(true) }))
  useEffect(() => writeStorage('masakapa-language', lang), [lang]); useEffect(() => writeStorage('masakapa-favorites', favorites), [favorites]); useEffect(() => writeStorage('masakapa-grocery-list', groceryList), [groceryList]); useEffect(() => { if (mainRef.current) mainRef.current.scrollTop = 0 }, [screen, activeRecipe])
  const toggleFavorite = id => setFavorites(items => items.includes(id) ? items.filter(item => item !== id) : [...items, id]); const addMissing = (recipe, ingredients, servings = recipe.defaultServings) => setGroceryList(items => { const ids = new Set(items.map(item => item.id)); const additions = ingredients.filter(item => !ids.has(`${recipe.id}-${item.id}`)).map(item => ({ id: `${recipe.id}-${item.id}`, ingredientId: item.id, name: item.name, amount: scaleIngredientAmount(item.amount, recipe.defaultServings, servings), recipeTitle: recipe.name, checked: false })); return [...items, ...additions] }); const openRecipe = (recipe, missingCore) => { window.history.pushState({ view: 'detail' }, ''); setActiveRecipe({ ...recipe, ...(missingCore === undefined ? {} : { missingCore }), onAddMissing: addMissing }) }
  useEffect(() => { const handlePopState = () => setActiveRecipe(null); window.addEventListener('popstate', handlePopState); return () => window.removeEventListener('popstate', handlePopState) }, []); const handleNavigate = nextScreen => { if (activeRecipe) { setActiveRecipe(null); if (window.history.state?.view === 'detail') window.history.back() } if (nextScreen === 'discover') setFilter('Semua'); setScreen(nextScreen) }; const onToggleLanguage = () => setLang(value => value === 'ms' ? 'en' : 'ms')
  const t = translations[lang]; const nav = <BottomNav screen={screen} onNavigate={handleNavigate} groceryCount={groceryList.length} lang={lang} />; const toast = updateAvailable && <div className="update-toast"><span>{t.ui.update}</span><button onClick={() => updateSW(true)}>{t.ui.refresh}</button></div>; const view = activeRecipe ? <RecipeDetail recipe={activeRecipe} isFavorite={favorites.includes(activeRecipe.id)} onToggleFavorite={toggleFavorite} onOpenRecipe={openRecipe} onBack={() => window.history.state?.view === 'detail' ? window.history.back() : setActiveRecipe(null)} onAddMissing={addMissing} lang={lang} onToggleLanguage={onToggleLanguage} /> : screen === 'matcher' ? <Matcher openRecipe={openRecipe} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} favorites={favorites} toggleFavorite={toggleFavorite} lang={lang} onToggleLanguage={onToggleLanguage} /> : screen === 'grocery' ? <GroceryList groceryList={groceryList} onToggleItem={id => setGroceryList(items => items.map(item => item.id === id ? { ...item, checked: !item.checked } : item))} onClearChecked={() => setGroceryList(items => items.filter(item => !item.checked))} onClearAll={() => setGroceryList([])} lang={lang} onToggleLanguage={onToggleLanguage} /> : screen === 'favorites' ? <Favorites openRecipe={openRecipe} favorites={favorites} toggleFavorite={toggleFavorite} lang={lang} onToggleLanguage={onToggleLanguage} onExplore={() => handleNavigate('discover')} /> : <Discover openRecipe={openRecipe} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} favorites={favorites} toggleFavorite={toggleFavorite} lang={lang} onToggleLanguage={onToggleLanguage} />
  return <div className="app-shell"><div className="h-screen max-w-md mx-auto flex flex-col overflow-hidden bg-[#FDFBF7] shadow-2xl relative"><main ref={mainRef} className="flex-1 overflow-y-auto px-4 py-3">{view}</main><footer className="shrink-0 border-t border-stone-200 bg-white z-50">{nav}</footer>{toast}</div></div>
}
